### ISSUE TITLE
influxdb integration

### ISSUE THREAD

**Issue by evon800c** [matthias-bs/BresserWeatherSensorLW#33]
HI,
I think this isn't the best way but I think I've made a mess.
I'll pass you the material here.

Davide
[document.zip](https://github.com/matthias-bs/BresserWeatherSensorLW/files/15363398/document.zip)

**Comment by matthias-bs** [comment]
Hi,
I'm currently busy with a big feature, but I will come back to this issue soon.
Cheers
Matthias

**Comment by evon800c** [comment]
Hi, @matthias-bs ,
feel free to public doc when and where you want. :-)
Davide
